#Vivienne Qie, Amy Liu, and Nathan Cheek
#qievi@gatech.edu, aliu66@gatech.edu, and ncheek@gatech.edu
#We worked on the homework assignment together, using only this semester's course materials.

from Myro import *
init()

def sceneOne(): #Peach (the robot) is dancing in a field by herself.
    wait(5)
    turnBy(90, "deg")
    wait(5)
    forward(1,0.3)
    wait(5)
    forward(1,0.3)
    wait(5)
    forward(1,0.3)
    wait(5)
    foward(1,0.3)
    wait(5)
    turnBy(-90,"deg")
    wait(5)
    turnBy(-90,"deg")
    wait(5)
    forward(1,0.3)
    wait(5)
    forward(1,0.3)
    wait(5)
    forward(1,0.3)
    wait(5)
    forward(1,0.3)
    wait(5)
    forward(1,0.3)
    wait(5)
    forward(1,0.3)
    wait(5)
    turnBy(90,"deg")
    wait(5)
    turnBy(90,"deg")
    wait(5)
    forward(1,0.3)
    wait(5)
    forward(1,0.3)
    wait(5)
    forward(1,0.3)
    wait(5)
    turnBy(-90,"deg")
    wait(5)
    turnBy(-72,"deg")
    wait(5)
    turnBy(-72,"deg")
    wait(5)
    turnBy(-72,"deg")
    wait(5)
    turnBy(-72,"deg")
    wait(5)
    turnBy(-72,"deg")

def sceneTwo(): #Bowser (robot) comes and chases Peach (prop) around and eventually catches up to her.
    wait(5)
    forward(1,0.4)
    wait(5)
    forward(1,0.4)
    wait(5)
    wait(5) #Peach sees Bowser
    wait(5) #Peach starts running away
    forward(1,0.4)
    wait(5)
    forward(1,0.4)
    wait(5)
    forward(1,0.4)
    wait(5)
    forward(1,0.4)
    wait(5)
    forward(1,0.4)
    wait(5)
    forward(1,0.4)
    wait(5)
    turnBy(180, "deg")
    wait(5)
    forward(1,0.4)
    wait(5)
    forward(1,0.4)
    wait(5)
    forward(1,0.4)
    wait(5)
    forward(1,0.4)
    wait(5) #Bowser captures Peach
    forward(1,0.4)
    wait(5)
    forward(1,0.4)
    wait(5)
    forward(1,0.4)
    wait(5)
    forward(1,0.4)

def sceneThree(): #Bowser takes Peach back to his castle
    wait(5)
    forward(1,0.3)
    wait(5)
    forward(1,0.3)
    wait(5)
    forward(1,0.3)
    wait(5)
    forward(1,0.3)
    wait(5)
    forward(1,0.3)
    wait(5)
    forward(1,0.3)
    wait(5)
    wait(5) #Bowser (robot) puts Peach (prop) in cage
    turnBy(-90,"deg")
    wait(5)
    turnBy(-90,"deg")
    wait(5)
    forward(1,0.3)
    wait(5)
    forward(1,0.3)
    wait(5)
    forward(1,0.3)
    wait(5)
    turnBy(90,"deg")

def sceneFour(): #Mario (robot) comes and fights Bowser (prop)
    wait(5)
    forward(1,0.3)
    wait(5)
    forward(1,0.3)
    wait(5)
    forward(1,0.3)
    wait(5)
    forward(1,0.3)
    wait(5)
    forward(1,0.3)
    wait(5)
    forward(1,0.3)
    wait(5)
    backward(1,0.3)
    wait(5)
    forward(1,0.3)
    wait(5)
    forward(1,0.3)
    wait(5)
    forward(1,0.3)
    wait(5)
    forward(1,0.3)
    wait(5)
    turnBy(180,"deg")
    wait(5)
    turnBy(180,"deg")
    wait(5)
    turnBy(180,"deg")
    wait(5)
    turnBy(180,"deg")

def sceneFive(): #Mario (robot) saves Peach (prop)
    wait(5)
    forward(1,0.5)
    wait(5)
    forward(1,0.5)
    wait(5)
    forward(1,0.5)
    wait(5)
    forward(1,0.5)
    wait(5)
    forward(1,0.5)
    wait(5)
    forward(1,0.5)
    wait(5)
    forward(1,0.5)
    wait(5)
    forward(1,0.5)
    wait(5)
    forward(1,0.5)
    wait(5)
    forward(1,0.5)
    wait(5)
    forward(1,0.5)
    wait(5)
    forward(1,0.5)
    wait(5)
    forward(1,0.5)
    wait(5)
    forward(1,0.5)
    wait(5)
    forward(1,0.5)
